### ISSUE TITLE
Error in emulator

### ISSUE THREAD

**Issue by emilisev** [ga-zelle/APS-what-if#2]
Hi

I'm getting this error with the attached log : 

> Problem in emulator_core.py
>   File "...\software\emulator_GUI.py", line 810, in sub_emul
>     loopInterval, thisTime, extraSMB, CarbReqGram, CarbReqTime, lastCOB, fn_first = parameters_known(afil.get(), gopt, vfil.get(), useStart, useStopp, entries, m, my_decimal)
>                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "...\software\emulator_core.py", line 2461, in parameters_known
>     cont = scanLogfile(fn, entries)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "...\software\emulator_core.py", line 1442, in scanLogfile
>     cont = TreatLoop(dataStr[8:], log, lcount, fn)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "...\software\emulator_core.py", line 750, in TreatLoop
>     if ins_Req > 0.0:                            # can be empty string; was >0.2 before
>        ^^^^^^^^^^^^^
> '>' not supported between instances of 'NoneType' and 'float'
> 

[AndroidAPS._2024-06-20_02-00-29_.0.zip](https://github.com/user-attachments/files/15918525/AndroidAPS._2024-06-20_02-00-29_.0.zip)

**Comment by ga-zelle** [comment]
Thanks for adding the logfile. In your original run there was a "division by 0" error for some reason I did not track down. Therefore the results of the loop at 02:39 and 02:44 are invalid. You can see several glucose predictions are **NaN**, i.e "Not-a-Number". That cannot be "digested" by the emulator.

So I can run your example with a start time of 2024-04-20T02:50 without problems

**Comment by emilisev** [comment]
Ok thanks for looking into it :-) Not sure why this happened, I didn't notice anything special happening at that moment, and never had this error on other log files.
